### ISSUE TITLE
Failed to execute 'requestAnimationFrame' on 'Window': The callback provided as parameter 1 is not a function.

### ISSUE THREAD

**Issue by zloyreznic** [tamtakoe/oi.select#55]
angular v1.2.26
oi.select        full: '0.2.15',
            
```javascript
TypeError: Failed to execute 'requestAnimationFrame' on 'Window': The callback provided as parameter 1 is not a function.
    at TypeError (native)
    at http://localhost:63342/TF-API/Client-UI/src/jslibs/angular.js:11860:20
    at http://localhost:63342/TF-API/Client-UI/src/jslibs/angular.js:4344:31
    at async (http://localhost:63342/TF-API/Client-UI/src/jslibs/angular.js:4179:13)
    at Object.$provide.$get.fn.removeClass (http://localhost:63342/TF-API/Client-UI/src/jslibs/angular.js:4311:9)
    at Object.fn (http://localhost:63342/TF-API/Client-UI/src/jslibs/select/select-tpls.js:545:69)
    at Scope.promises.$get.Scope.$digest (http://localhost:63342/TF-API/Client-UI/src/jslibs/angular.js:12541:29)
    at Scope.promises.$get.Scope.$apply (http://localhost:63342/TF-API/Client-UI/src/jslibs/angular.js:12806:24)
    at http://localhost:63342/TF-API/Client-UI/src/jslibs/angular.js:14314:36
    at completeOutstandingRequest (http://localhost:63342/TF-API/Client-UI/src/jslibs/angular.js:4397:10)(anonymous function) @ angular.js:10072str2.$get @ angular.js:7364promises.$get.Scope.$digest @ angular.js:12560promises.$get.Scope.$apply @ angular.js:12806(anonymous function) @ angular.js:14314completeOutstandingRequest @ angular.js:4397(anonymous function) @ angular.js:4705
angular.js:10072 TypeError: Failed to execute 'requestAnimationFrame' on 'Window': The callback provided as parameter 1 is not a function.
    at TypeError (native)
    at http://localhost:63342/TF-API/Client-UI/src/jslibs/angular.js:11860:20
    at http://localhost:63342/TF-API/Client-UI/src/jslibs/angular.js:4344:31
    at async (http://localhost:63342/TF-API/Client-UI/src/jslibs/angular.js:4179:13)
    at Object.$provide.$get.fn.removeClass (http://localhost:63342/TF-API/Client-UI/src/jslibs/angular.js:4311:9)
    at Object.fn (http://localhost:63342/TF-API/Client-UI/src/jslibs/select/select-tpls.js:551:66)
    at Scope.promises.$get.Scope.$digest (http://localhost:63342/TF-API/Client-UI/src/jslibs/angular.js:12541:29)
    at Scope.promises.$get.Scope.$apply (http://localhost:63342/TF-API/Client-UI/src/jslibs/angular.js:12806:24)
    at http://localhost:63342/TF-API/Client-UI/src/jslibs/angular.js:14314:36
    at completeOutstandingRequest (http://localhost:63342/TF-API/Client-UI/src/jslibs/angular.js:4397:10)(anonymous function) @ angular.js:10072str2.$get @ angular.js:7364promises.$get.Scope.$digest @ angular.js:12560promises.$get.Scope.$apply @ angular.js:12806(anonymous function) @ angular.js:14314completeOutstandingRequest @ angular.js:4397(anonymous function) @ angular.js:4705
'''

**Comment by zloyreznic** [comment]
Есть кто?

**Comment by vdzundza** [comment]
I've this issue too.

**Comment by dzmitry-kankalovich** [comment]
I assume thats because oi-select is not angular 1.3 compatible and uses $animate contract from angular 1.3 version.

**Comment by tamtakoe** [comment]
@zloyreznic I'm sorry, it was a lot of work. I fix it in v. 0.2.16

**Comment by zloyreznic** [comment]
Спасибо

**Comment by parag1111** [comment]
var requestId = requestAnimFrame(this.animate.bind(this));

Update May 2019

If you can use ES6 you can employ an arrow function, which will maintain scope like this:

let requestId = requestAnimFrame(() => { this.animate(); });

**Comment by LukyVj** [comment]
I downvoted the latest, because it's a pure copy paste from StackOverflow https://stackoverflow.com/questions/22039180/failed-to-execute-requestanimationframe-on-window-the-callback-provided-as
